on:
  push:
name: Push
env:
  RACK_SDK_VERSION: 1.1.6
jobs:
  buildLinux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build Linux
      uses: ./.github/actions/build_linux
  buildWindows:
    name: Build Windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build Windows
      uses: ./.github/actions/build_win
  buildOsx:
    name: Build OSX
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build OSX
      uses: ./.github/actions/build_osx
