name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for contributing this your first issue! Please rest assured that I'll look into it as soon as possible..'' first issue'
        pr-message: 'Waow! Thanks a lot! I'll look into it as soon as possible!'' first pr'
